version: 2
jobs:
  build:
    docker:
      - image: circleci/python:2.7
      - image: tkislan/kodi-simulator
    environment:
        KODI_HOST: http://localhost:8080
    working_directory: ~/app
    steps:
      - checkout

      - run:
          name: Set PYTHONPATH environment variable
          command: echo 'export PYTHONPATH=${HOME}/app/mock:${HOME}/app/resources/lib:${HOME}/app/resources' >> $BASH_ENV

      - run:
          name: Export
          command: export

      - run:
          name: Install Test dependencies
          command: sudo pip install pylint flake8

      - run:
          name: Install dependencies
          command: ./install-dependencies.sh

      - run:
          name: Run Linter
          command: ./run-linter.sh

      - run:
          name: Wait for kodi simulator
          command: ./wait-for-kodi-simulator.sh

      - run:
          name: Run tests
          command: python -m unittest discover -s tests/

      - run:
          name: Run Fuzzy tests
          environment:
            DISABLE_NGRAM_INDEX: "1"
          command: python -m unittest discover -s tests/
